### ISSUE TITLE
Bug on edge selection in case of 2 aligned edges

### ISSUE THREAD

**Issue by lelandaisb** [LIHPC-Computational-Geometry/tune#29]
If 2 edges are on the same line, the first one is selected even if the mouse click is on the second one.
Ex: list of two edges [e1, e2] (order is important)
x-------e1------x------e2-------x
If you click on e2, e1 will be selected.

**Comment by franck-ledoux** [comment]
On peut voir la méthode isIn ligne 114 de https://github.com/LIHPC-Computational-Geometry/gmds/blob/main/math/src/Segment.cpp

**Comment by nicolaslg** [comment]
The previous fix protected against selecting the incorrect edge in one direction but not the other
``` python
p1 = math.Vector2(0.5, 0.0)
(Edge.is_pt_on_segment(1.0, 0.0, 2.0, 0.0, p1, tolerance)) # returns true but should return false
```
